version: '3.8'

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
     - "80:80"
    depends_on:
      api:
        condition: service_started

  api:
    image: gysborn/diploma:homework-38
    env_file: .env
    restart: always
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: gysborn/diploma:homework-38
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: postgres
    command: python manage.py migrate

  bot:
    image: gysborn/diploma:deep-bot
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file: .env
    restart: always
    environment:
      DB_HOST: postgres
    command: python manage.py runbot

  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} " ]
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: